name: ci-cd
on: 
  pull_request:
    types: 
      - opened
    branches: 
      - "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: dotnet test

  deploy:
    runs-on: ubuntu-latest
    env: 
      SITE_URL: ${{vars.SITE_URL}}
    steps:
      - run: echo "deploying to $SITE_URL"
