# Create a workflow that triggers manually and:
  # 1. Print our SLOGAN
  # 2. Guess MY_MAGIC_NUMBER

name: Print variables and secrets

on: 
  workflow_dispatch:
    inputs:
      num:
        type: number
        description: "select number to guess"
        default: ""

jobs: 
  print-SLOGAN:
    runs-on: ubuntu-latest
    env: 
      SLOGAN: ${{ vars.Slogan }}
      
      
    steps:
      - run: echo ${{ vars.SLOGAN }}
      - run: echo $SLOGAN

  guess-magic-number:
    runs-on: ubuntu-latest
    env:
      MY_MAGIC_NUMBER: ${{ secrets.MY_MAGIC_NUMBER }}
      
    steps:   
    - name: Print Magic Number
      run: echo ${{ secrets.MY_MAGIC_NUMBER }}
    
    - name: Print Magic Number with env variable
      run: echo $MY_MAGIC_NUMBER

    - name: Guess Magic Number
      if: always()
      run: |
        if ["${{ secrets.MY_MAGIC_NUMBER }}" = "${{ inputs.num }}"]; then
          echo "Yay! The maagic number was: ${{ inputs.num }}"
        fi

    
      
    

