# Create a workflow that triggers manually and:
  # 1. Print our SLOGAN
  # 2. Guess MY_MAGIC_NUMBER

name: Print variables and secrets

on: workflow_dispatch

jobs: 
  print-SLOGAN-SECRET:
    runs-on: ubuntu-latest
    steps:
    - name: print SLOGAN
      run: echo "${{ vars.SLOGAN }}
    - name: print SECRET
      run: echo "${{ secrets.MY_MAGIC_NUMBER }}
    
      
    

